# -*- coding: utf-8 -*-
"""DV_Programming_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uSN7m6HtAsezhp0OriXsIZ7Ynb-gKvOs

Step 1 : Description about the dataset

The dataset, bd_students_per.csv, consists of 8,612 rows and 24 columns, with details about students in Bangladesh, including demographics, academic performance, parental involvement, and extracurricular activities. Below is a brief description of key variables:

	•	Demographic Details: Includes age, gender, and location.
	•	Academic Performance: Scores in english, math, science, social_science, and art_culture.
	•	Parental Involvement: Includes variables like mother_education, father_education, and guardian.
	•	Other Factors: Includes studytime, attendance, and whether students participate in extracurricular activities.

This dataset can help explore the relationship between academic performance and influencing factors like parental involvement, location, or extracurricular activities.

Step 2: Dataset Summary

Key findings:

	•	Age: Ranges from 10 to 24 years, with an average of ~16.6 years.
	•	Academic Scores: Most scores (English, Math, etc.) cluster around 70-85.
	•	Attendance: Ranges from 30% to 100%, with a mean of 74%.

Step 3: Data Cleaning
"""

import pandas as pd

# Load the uploaded CSV file
file_path = 'bd_students_per.csv'
data = pd.read_csv(file_path)

# Display the first few rows to understand its structure
data.head()
data.info()
data.describe()

# Check for missing values and invalid entries
missing_summary = data.isnull().sum()
print(missing_summary)

# Drop rows with any missing values
cleaned_data = data.dropna()

# Verify the cleaned dataset
cleaned_summary = cleaned_data.isnull().sum()
cleaned_summary

"""Step 4: Variable Selection

For analysis, the variables selected are:

	1.	Academic Scores (english, math, science, etc.): To evaluate academic performance.
	2.	Parental Involvement: Includes variables like mother_education, father_education, and guardian.
	3.	Attendance: To observe its impact on performance.

The goal is to explore how factors like parental involvement and attendance influence academic performance.
"""

import pandas as pd
import matplotlib.pyplot as plt

# Step 1: Calculate the Average Academic Score for each student
cleaned_data['Average_Score'] = cleaned_data[['english', 'math', 'science', 'social_science', 'art_culture']].mean(axis=1)

# Step 2: Cluster Students Based on Academic Performance
def performance_cluster(score):
    if score < 60:
        return 'Low'
    elif 60 <= score < 85:
        return 'Average'
    else:
        return 'High'

cleaned_data['Performance_Cluster'] = cleaned_data['Average_Score'].apply(performance_cluster)

# Assuming Parental_Involvement_Score is a column in the dataset
def parental_involvement_cluster(status):
    if status == 'Yes':
        return 'High'
    else:
        return 'Low'

# Step 3: Cluster Students Based on Attendance
bins = [0, 50, 75, 100]
labels = ['Low Attendance', 'Moderate Attendance', 'High Attendance']
cleaned_data['Attendance_Cluster'] = pd.cut(cleaned_data['attendance'], bins=bins, labels=labels)

# checking for parental involvement score
if 'parental_involvement' in cleaned_data.columns:
    cleaned_data['Parental_Involvement_Cluster'] = cleaned_data['parental_involvement'].apply(parental_involvement_cluster)
else:
    print("Parental_Involvement_Score column not found in the dataset.")

# Step 4: Analyze Clusters
performance_counts = cleaned_data['Performance_Cluster'].value_counts()
attendance_summary = cleaned_data.groupby('Attendance_Cluster')['Average_Score'].mean()
parental_involvement_summary = cleaned_data.groupby('Parental_Involvement_Cluster')['Average_Score'].mean()

# Step 5: Visualization

# 5.1: Bar chart for Academic Performance Clusters
plt.figure(figsize=(10, 5))
performance_counts.plot(kind='bar', color=['red', 'orange', 'green'])
plt.title('Number of Students in Each Performance Cluster')
plt.xlabel('Performance Cluster')
plt.ylabel('Number of Students')
plt.xticks(rotation=0)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# 5.2: Line chart for Academic Performance vs Attendance Clusters
plt.figure(figsize=(10, 5))
attendance_summary.plot(kind='line', marker='o', color='blue', linestyle='--')
plt.title('Academic Performance vs Attendance Clusters')
plt.xlabel('Attendance Cluster')
plt.ylabel('Average Academic Score')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

# 6.3: Line chart for Academic Performance vs Parental Involvement Clusters
plt.figure(figsize=(10, 5))
parental_involvement_summary.plot(kind='line', marker='o', color='purple', linestyle='--')
plt.title('Academic Performance vs Parental Involvement Clusters')
plt.xlabel('Parental Involvement Cluster')
plt.ylabel('Average Academic Score')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

# Print the summarized results
print("Performance Cluster Counts:")
print(performance_counts)

print("\nAttendance Cluster Summary:")
print(attendance_summary)

print("\nParental Involvement Cluster Summary:")
print(parental_involvement_summary)

"""Description of the Analysis:

This analysis investigates the relationship between academic performance, attendance, and parental involvement among students. The dataset contains various student attributes such as subject scores, attendance percentages, and parental involvement. The goal is to classify students into different clusters based on their academic performance, attendance, and parental involvement, and analyze how these factors correlate with each other.

Steps in the Analysis:

	1.	Calculate Average Academic Score: The average score for each student was calculated by averaging their scores in five subjects: English, Math, Science, Social Science, and Art Culture.
	2.	Performance Clustering: Students were classified into three performance clusters based on their average academic score:
	•	Low: Average score less than 60
	•	Average: Average score between 60 and 84
	•	High: Average score 85 or higher
	3.	Attendance Clustering: Students were classified into three attendance clusters:
	•	Low Attendance: Attendance percentage less than 50%
	•	Moderate Attendance: Attendance percentage between 50% and 75%
	•	High Attendance: Attendance percentage between 75% and 100%
	4.	Parental Involvement Clustering: Students were classified based on their parental involvement:
	•	High: If the parent is involved (marked as Yes)
	•	Low: If the parent is not involved (marked as No)
	5.	Analysis: The data was analyzed to understand the number of students in each cluster and the average academic score for each cluster of attendance and parental involvement.

Summary of the Results:

	1.	Performance Cluster Counts:
	•	Average: 3,984 students fall into the “Average” performance category.
	•	High: 2,633 students are in the “High” performance category.
	•	Low: 1,982 students are in the “Low” performance category.
	2.	Attendance Cluster Summary:
	•	Low Attendance: Average score = 66.25
	•	Moderate Attendance: Average score = 68.62
	•	High Attendance: Average score = 80.95
	•	This shows that students with higher attendance tend to have higher average academic scores.
	3.	Parental Involvement Cluster Summary:
	•	High Parental Involvement: Average score = 74.30
	•	Low Parental Involvement: Average score = 74.01
	•	The difference in average scores between high and low parental involvement is minimal, suggesting that parental involvement may not have a significant impact on academic performance in this dataset.

Visualizations:

	•	Bar Chart: A bar chart was used to show the distribution of students across the performance clusters (Low, Average, High).
	•	Line Chart (Attendance vs. Academic Performance): A line chart showed the relationship between attendance and average academic performance.
	•	Line Chart (Parental Involvement vs. Academic Performance): A line chart showed the relationship between parental involvement and average academic performance.

Conclusion:

	•	The analysis suggests that higher attendance is positively correlated with better academic performance. However, parental involvement does not show a significant difference in academic performance.

This analysis helps provide insights into how attendance and parental involvement affect student academic outcomes.
"""